prefix: 'b:'
github: https://github.com/BlackListener/BlackListener/
lang: en
notifyRep: 1
banRep: 5
dump_url:
data_baseurl:
version: '1.1.2'
repl:
  prefix: '> '
  disable: false
logger:
  debug: false
  style: original
  # Options:
  # maven: Maven style
  # npm: npm like style
  # original(or otherize): Original BlackListeners style
